version: '3'
services:
  react-docker-sample:
    container_name: react-sample
    image: node:18
    tty: true
    volumes:
      - ../:/home/node/app
      - ../:/workspaces:cached
    ports:
      - ${VITE_CLIENT_PORT}:${VITE_HOST_PORT}
    command: /bin/sh -c "while sleep 1000; do :; done"